BookingApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from clients import views as clients_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('news/', include('blog.urls')),
    # path('register/', include('clients.urls')),
    path('personnel/', include('personnel.urls')),
    path('client/', include('clients.urls')),
    path('register/', clients_views.register, name='register'),
    # path('profile/', website_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='website/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='website/logout.html'), name='logout'),
    path('reservations/', include('reservations.urls'))

]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
)

urlpatterns = [
    path('', PostListView.as_view(), name='news'),
    path('<int:pk>', PostDetailView.as_view(), name='post-detail'),
    path('new/', PostCreateView.as_view(), name='post-create'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='post-update'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='post-delete')

]

personnel/urls.py
from django.urls import path
from .views import PersonnelList, PersonnelUpdate, PersonnelCreate, PersonnelDelete

urlpatterns = [

    path('', PersonnelList.as_view(), name='personnel_list'),
    path('update/<int:pk>/', PersonnelUpdate.as_view(), name='personnel_update'),
    path('create/', PersonnelCreate.as_view(), name='personnel_create'),
    path('delete/<int:pk>/', PersonnelDelete.as_view(), name='personnel_delete'),

]

personnel/models.py
from PIL import Image
from django.contrib.auth.models import User
from django.db import models
from website.models import Service
from clients.models import ClientProfile


class PersonnelProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(default=None, null=True)
    address = models.CharField(max_length=200)
    services = models.ManyToManyField(Service)
    image = models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

reservations/models.py
from django.db import models
import calendar
import datetime
from clients.models import ClientProfile
from personnel.models import PersonnelProfile
from website.models import Service


class WorkDay(models.Model):
    day_choices = [(str(i), calendar.day_name[i]) for i in range(7)]
    name = models.CharField(max_length=9, choices=day_choices, default='1', unique=True)

    def __str__(self):
        return self.get_name_display()


class Schedule(models.Model):
    user = models.OneToOneField(PersonnelProfile, on_delete=models.CASCADE)
    availability_days = models.ManyToManyField(WorkDay)
    start_hour = models.TimeField()
    end_hour = models.TimeField()

    def __str__(self):
        return f'Schedule of {self.user.user.first_name} {self.user.user.last_name}'


class MonthlySchedule(models.Model):
    user = models.ForeignKey(PersonnelProfile, on_delete=models.CASCADE)
    year_choices = [(str(datetime.date.today().year), datetime.date.today().year),
                    (str(datetime.date.today().year + 1), datetime.date.today().year + 1)]
    month_choices = [(str(i), calendar.month_name[i]) for i in range(1, 13)]
    year = models.CharField(max_length=4, choices=year_choices, default='1')
    month = models.CharField(max_length=9, choices=month_choices, default='1')

    def get_month_name(self):
        return calendar.month_name[int(self.month)]

    def __str__(self):
        return f'{calendar.month_name[int(self.month)]} {self.year}'


class DailySchedule(models.Model):
    month = models.ForeignKey(MonthlySchedule, on_delete=models.CASCADE)
    day = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    break_start = models.TimeField(blank=True, null=True)
    break_end = models.TimeField(blank=True, null=True)

    def __str__(self):
        return f'{self.day.day}/{self.month.month}/{self.month.year}'


class Reservation(models.Model):
    user = models.ForeignKey(PersonnelProfile, on_delete=models.PROTECT)
    client = models.ForeignKey(ClientProfile, on_delete=models.PROTECT)
    service = models.ForeignKey(Service, on_delete=models.PROTECT)
    date = models.DateField(blank=True)
    start_time = models.TimeField(blank=True)

    def __str__(self):
        return f'Reservation Date: {self.date} - {self.start_time}\n' \
               f'Personnel: {self.user.user.first_name} {self.user.user.last_name} ' \
               f'Client: {self.client.user.first_name} {self.client.user.last_name}'

personnel/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import PersonnelProfile


class PersonnelUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'is_active']


class PersonnelCreateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name']
        widgets = {
            'password': forms.PasswordInput()
        }


class PersonnelProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = PersonnelProfile
        fields = ['birth_date', 'address', 'services', 'image']
        widgets = {
            'services': forms.CheckboxSelectMultiple()
        }


class SendCredentialsForm(forms.Form):
    send_credentials = forms.BooleanField(required=False, label='Send credentials to specified e-mail')

personnel/views.py
from .models import PersonnelProfile
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views.generic import ListView, UpdateView, CreateView, DeleteView
from .forms import PersonnelUpdateForm, PersonnelProfileUpdateForm, PersonnelCreateForm, SendCredentialsForm
from website.messages import send_email
from BookingApp.settings import PLATFORM_NAME, PLATFORM_URL


class PersonnelList(LoginRequiredMixin, UserPassesTestMixin, ListView):

    model = PersonnelProfile
    context_object_name = 'objects'

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False


class PersonnelCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):

    @staticmethod
    def get(request):
        form = PersonnelCreateForm()
        form2 = PersonnelProfileUpdateForm()
        form3 = SendCredentialsForm()
        context = {
            'user_form': form,
            'profile_form': form2,
            'credentials_form': form3
        }
        return render(request, 'personnel/personnel_create.html', context)

    @staticmethod
    def post(request):
        form = PersonnelCreateForm(request.POST)
        form2 = PersonnelProfileUpdateForm(request.POST)
        form3 = SendCredentialsForm(request.POST)

        if form.is_valid() and form2.is_valid():
            user = form.save(commit=False)
            user.is_staff = True
            form.save()
            profile = form2.save(commit=False)
            profile.user = form.instance
            form2.save()

            if form3.is_valid():
                try:
                    if form3.cleaned_data['send_credentials'] is True:
                        details = {
                            'recipient': user.email,
                            'subject': f'Account was created for you at {PLATFORM_NAME}',
                            'message': f'Hello Dear {user.first_name}!\n Please login to the system at {PLATFORM_URL} \b'
                                       f'Login credentials -  Username: {user.username} password: {user.password}'
                        }
                        send_email(details)
                except AttributeError:
                    pass

        return redirect('personnel_list')

    def test_func(self):
        if self.request.user.is_superuser:
            return True
        return False


class PersonnelUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):

    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=kwargs['pk'])
        form = PersonnelUpdateForm(instance=user)
        form2 = PersonnelProfileUpdateForm(instance=user.personnelprofile)

        data = {
            'first_name': user.first_name,
            'email': user.email,
            'image': user.personnelprofile.image.url,
            'id': user.id,
        }

        context = {
           'user_form': form,
           'profile_form': form2,
            'data': data
        }

        return render(request, 'personnel/personnel_update.html', context)

    def post(self, request, *args, **kwargs):
        user = User.objects.get(pk=kwargs['pk'])
        form = PersonnelUpdateForm(request.POST, instance=user)
        form2 = PersonnelProfileUpdateForm(request.POST, request.FILES, instance=user.personnelprofile)

        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return redirect('personnel_list')

    def test_func(self):
        if self.request.user.is_superuser:
            return True
        return False


class PersonnelDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = User
    success_url = '/personnel'
    template_name = 'personnel/user_confirm_delete.html'

    def test_func(self):
        if self.request.user.is_superuser:
            return True
        return False

personnel/templates/personnel/personnel_create.html
{% extends 'website/home.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="/media/profile_pics/default.jpg">
            <div class="media-body">
                <h2 class="account-heading">New User</h2>
            </div>
        </div>
    </div>
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ user_form|crispy }}
                {{ profile_form|crispy }}
                {{ credentials_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Create</button>
                <input type="button" value="Go back" class="btn btn-outline-info" onclick="history.back()">
            </div>
        </form>
    </div>

{% endblock %}

personnel/templates/personnel/personnel_update.html
{% extends 'website/home.html' %}
{% load crispy_forms_tags %}
{% block content %}
        <div class="content-section">
            <div class="media">
                <img class="rounded-circle account-img" src="{{ data.image }}">
                <div class="media-body">
                    <h2 class="account-heading">{{ data.first_name }}</h2>
                    <p class="text-secondary">{{ data.email }}</p>
                </div>
            </div>
        </div>
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Edit profile</legend>
                {{ user_form|crispy }}
                {{ profile_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
                <a href="{% url 'personnel_delete' data.id %}" class="btn btn-outline-danger">Delete</a>
                <input type="button" value="Go back" class="btn btn-outline-info" onclick="history.back()">
            </div>
        </form>
    </div>

{% endblock %}

personnel/templates/personnel/personnelprofile_list.html
{% extends "website/home.html" %}
{% block content %}
    {% for object in objects %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ object.image.url }}">
            <div class="media-body">
                <div class="article-metadata">
                    {% if request.user.is_superuser %}
                    <a class="mr-2" href="{% url 'personnel_update' object.user.id %}">{{ object.user.first_name }} {{ object.user.last_name }}</a>
                    {% else %}
                    <a class="mr-2">{{ object.user.first_name }} {{ object.user.last_name }}</a>
                    {% endif %}
                    <small class="text-muted">{{ object.birth_date|date:'d M Y' }}</small>
                </div>
                <p class="article-content">{{ object.user.email }}</p>
                {% if object.monthlyschedule_set %}
                    <a href="{% url 'monthly_schedule' object.id %}" class="btn btn-outline-info">Monthly schedule</a>
                {% endif %}
                {% if object.schedule %}
                <a href="{% url 'schedule'  object.id %}" class="btn btn-outline-info">Schedule</a>
                {% endif %}
            </div>
        </article>
    {% endfor %}
    {% if request.user.is_superuser %}
        <a href="{% url 'personnel_create' %}" class="btn btn-outline-info">Create Personnel Profile</a>
        <a href="{% url 'schedule_create' %}" class="btn btn-outline-info">Create Personnel Schedule</a>
        <a href="{% url 'schedule_import' %}" class="btn btn-outline-info">Import Schedule</a>

    {% endif %}
{% endblock content %}

personnel/templates/personnel/user_confirm_delete.html
{% extends 'website/home.html' %}
{% block content %}
    <div class="content-section">

        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete User</legend>
                <h2>Are you sure you want to delete this user ?  "{{ object.username }} ? </h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Delete</button>
                <input type="button" value="Go back" class="btn btn-outline-info" onclick="history.back()">
            </div>
        </form>
    </div>
{% endblock %}